version: '3'

services: 

    discovery-server:
        build: ./discovery-server
        ports: 
            - "8761:8761"
        restart: on-failure
        networks: 
            mynet:
                aliases: 
                    - discovery-server

    customer-db:
        build: ./customerDB
        depends_on: 
            - discovery-server
        restart: on-failure
        networks: 
            mynet:
                aliases: 
                    - customer-db
    
    customer-log-db:
        build: ./customerLogDB
        depends_on: 
            - discovery-server
        restart: on-failure
        networks: 
            mynet:
                aliases: 
                    - customer-log-db
                    
   
    customer-log:
        restart: on-failure
        build: ./customerLog
        ports: 
            - "8082:8082"
        depends_on: 
            - customer-log-db
            - discovery-server
            - api-gateway
        restart: on-failure
        networks: 
            mynet:
                aliases: 
                    - customer-log
    
    customer:
        build : ./customer
        ports: 
            - "8081:8081"
        depends_on: 
            - customer-db
            - customer-log
            - discovery-server
            - api-gateway
        restart: on-failure
        networks: 
            mynet:
                aliases: 
                    - customer
    
    api-gateway:
        build: ./api-gateway
        ports: 
            - "8080:8080"
        depends_on: 
            - discovery-server
        restart: on-failure
        networks: 
            mynet:
                aliases: 
                    - api-gateway 
    
    keycloak:
        build: ./keycloak
        restart: on-failure
        networks: 
            mynet:
                aliases: 
                    - keycloak

    config-server:
        build: ./config-server
        ports: "8083:8083"
        depends_on: 
            - discovery-server
        restart: on-failure
        networks: 
            mynet:
                aliases: 
                    - config-server

    frontend:
        build: ./frontend
        ports: "80:80"
        restart: on-failure
        networks: 
            mynet:
                aliases: 
                    - frontend


    


networks: 
    mynet:
        